export enum Types {
  // UserAuth actionTypes
  LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGIN_REQUESTED = "LOGIN_REQUESTED",
  LOGIN_WITH_TOKEN = "LOGIN_WITH_TOKEN",
  LOGOUT = "LOGOUT",
  LOGIN_DISABLE_ERRORS = "LOGIN_DISABLE_ERRORS",

}
