export enum LoginEnumTypes {
  LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGIN_REQUESTED = "LOGIN_REQUESTED",
  LOGIN_WITH_TOKEN = "LOGIN_WITH_TOKEN",
  LOGOUT = "LOGOUT",
  LOGIN_DISABLE_ERRORS = "LOGIN_DISABLE_ERRORS",
}

export enum SearchEnumTypes {
  SEARCH_REQUESTED = "SEARCH_REQUESTED",
  SEARCH_SUCCESSFULLY = "SEARCH_SUCCESSFULLY",
  SEARCH_FAILED = "SEARCH_FAILED",
  INITIALIZE_STATE = "INITIALIZE_STATE",
  SEARCH_NO_RESULTS = "SEARCH_NO_RESULTS",
}

export enum HeroTeamEnumTypes {
  MODIFY_HEROES_LIST = "MODIFY_HEROES_LIST",
  DELETE_ALL_HEROES = "DELETE_ALL_HEROES",
}
