export enum Types {
  // UserAuth actionTypes
  LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGIN_REQUESTED = "LOGIN_REQUESTED",
  LOGIN_WITH_TOKEN = "LOGIN_WITH_TOKEN",
  LOGOUT = "LOGOUT",
  LOGIN_DISABLE_ERRORS = "LOGIN_DISABLE_ERRORS",

  // All superhero data actionTypes
  FETCH_DATA_SUCCESSFULLY = "FETCH_DATA_SUCCESSFULLY",
  FETCH_DATA_FAILED = "FETCH_DATA_FAILED",
  FETCH_DATA_REQUESTED = "FETCH_DATA_REQUESTED",

  // Search hero by name
  SEARCH_HERO_SUCCESSFULLY = "SEARCH_HERO_SUCCESSFULLY",
  SEARCH_HERO_FAILED = "SEARCH_HERO_FAILED",
  SEARCH_HERO_REQUEST = "SEARCH_HERO_REQUEST",
}
